version: '3'
services:
  mp-nginx:
    image: nginx:1.10
    container_name: mp-nginx
    links:
      - mp-php-fpm
      - mp-php-cli
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - mp-php-fpm
      - mp-php-cli
  mp-php-fpm:
    build:
      context: ./
      dockerfile: docker/php-fpm.docker
    volumes:
      - ./:/var/www
    depends_on:
      - mp-postgres
  mp-php-cli:
    build:
      context: ./
      dockerfile: docker/php-cli.docker
    volumes:
      - ./:/var/www
    depends_on:
      - mp-postgres
  mp-postgres:
    image: postgres:11.2-alpine
    volumes:
      - ./docker/postgres:/var/lib/posgresql/data
    environment:
      POSTGRES_USER: mp
      POSTGRES_PASSWORD: mp
      POSTGRES_DB: mp
    ports:
      - '54321:5432'