version: '3'
services:
  mp-nginx:
    image: nginx:1.10
    container_name: mp-nginx
    links:
      - mp-php-fpm
      - mp-php-cli
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - mp-php-fpm
      - mp-php-cli
  mp-php-fpm:
    build:
      context: ./
      dockerfile: docker/php-fpm.docker
    volumes:
      - ./:/var/www
    depends_on:
      - mp-mysql
  mp-php-cli:
    build:
      context: ./
      dockerfile: docker/php-cli.docker
    volumes:
      - ./:/var/www
    depends_on:
      - mp-mysql
  mp-mysql:
    image: mysql:5.7
    container_name: project-mysql
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - "33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mp
      MYSQL_PASSWORD: mp
      MYSQL_DATABASE: mp